%% Prepares Settings


proc SettingsPrepare
    SoundTrack := false
    OptString (1) := "Sound Track"
    OptString (2) := "  Theatre"
    OptString (3) := "   Save"
    OptString (4) := "   World"
    SongName (1) := "Cat, Glass, Moon"
    SongName (2) := "Eternity"
    SongName (3) := "Night of Nights"
    SongName (4) := "Light My Fire"
    SongName (5) := "Instrumental"
    SongName (6) := "Grief"
    SongName (7) := "Sociometry"
    SongName (8) := "Blaze!"
    SongName (9) := "WataMote ED"
    SongName (10) := "Grimoire of the Rift"
    SongName (11) := "Premonition"
    SongName (12) := "Words put together"
    SongName (13) := "Where the wind rea.."
    SongName (14) := "Newborn Wind"
    SongName (15) := "Promise"
    SongName (16) := "Kaze No Tadori"
    SongName (17) := "Eternal"
    SongName (18) := "Kotoba-Tabadachi"
    SongName (19) := "Memory"
    SongName (20) := "Summer Lights"
    SongName (21) := "Remnants of a dream"
    SongName (22) := "Winter Fireworks"
    SongName (23) := "Saya's Song"
    SongName (24) := "Why, or why not"
    SongName (25) := "Kanon - The OST"
   SongDes (1) := "Searching for the Shade cat"
   SongDes (2) := "Once in a rift"
   SongDes (3) := "Synthesia Nightmare"
   SongDes (4) := "Shakugan No Shana"
   SongDes (5) := "Shakugan No Shana"
   SongDes (6) := "Corpse Bride"
   SongDes (7) := "Socio - Dissection"
   SongDes (8) := "Burning bright"
   SongDes (9) := "SA - It's not my fault!"
   SongDes (10) := "Opening the rift"
   SongDes (11) := "Premonition of the beginning"
   SongDes (12) := "Words that were put together"
   SongDes (13) := "Where the wind reaches"
   SongDes (14) := "Umaratete no kaze"
   SongDes (15) := "Promise - Angel Beats"
   SongDes (16) := "Kaze No Tadori - Ending"
   SongDes (17) := "Eternal - Orange Days"
   SongDes (18) := "Kotoba-Tabadachi"
   SongDes (19) := "Memory - Angel Beats"
   SongDes (20) := "Summer Lights - Natsukage"
   SongDes (21) := "Remnants of a dream - Yume No Ato"
   SongDes (22) := "Winter Fireworks - Kanon"
   SongDes (23) := "Saya's Song - Tokido Saya"
   SongDes (24) := "Why, or why not - Higurashi"
   SongDes (25) := "Extra - Kanon OST"
    TC (1) := 33
    TC (2) := 60
    TC (3) := 124
    TC (4) := 33
    TC (5) := 33
    TC (6) := 128
    TC (7) := 58
    TC (8) := 35
    TC (9) := 58
    TC (10) := 124
    TC (11) := 48
    TC (12) := 109
    TC (13) := 79
    TC (14) := 76
    TC (15) := 56
    TC (16) := 150
    TC (17) := 42
    TC (18) := 116
    TC (19) := 76
    TC (20) := 91
    TC (21) := 82
    TC (22) := 102
    TC (23) := 60
    TC (24) := 122
    TC (25) := 54
end SettingsPrepare
